export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_PEOPLE_FAIL = "GET_PEOPLE_FAIL";

export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";
export const GET_FILM_FAIL = "GET_FILM_FAIL";

export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";
export const GET_VEHICLES_FAIL = "GET_VEHICLES_FAIL";

export const GET_SPESIES_SUCCESS = "GET_SPESIES_SUCCESS";
export const GET_SPESIES_FAIL = "GET_SPESIES_FAIL";

export const GET_STARSHIP_SUCCESS = "GET_STARSHIP_SUCCESS";
export const GET_STARSHIP_FAIL = "GET_STARSHIP_FAIL";